apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 2
  selector:
      matchLabels:
        app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
        - name: conversaotemperatura
          image: rarandrade/conversao-temperatura-desafio:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080
    nodePort: 30500
  type: NodePort
